PatentMiner/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('sitesearch.urls',namespace="sitesearch")),
    url(r'^law_regulate/', include('law_regulate.urls',namespace="law_regulate")),
]

sitesearch/urls.py
from django.conf.urls import url

from . import views

app_name = 'law_regulate'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^word_search$', views.word_search, name='word_search'),
    url(r'^detail$', views.detail, name='detail'),
    url(r'^collect$', views.collect, name='collect'),
    url(r'^collection$', views.collection, name='collection'),
    url(r'^excel_export$', views.excel_export, name='excel_export'),

]

sitesearch/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models


# 主信息表
class PatentInfo(models.Model):
    patent_Id = models.CharField(max_length=100,primary_key=True)           # 专利唯一标识(主键)
    patent_name = models.CharField(max_length=300)                          # 专利名称
    appli_num = models.CharField(max_length=50)                             # 申请号（唯一）
    appli_time = models.CharField(max_length=50,null=True)                  # 申请时间
    appli_num2 = models.CharField(max_length=50, null=True)                 # 去掉小数点的申请号（用来标识同族）
    pub_num = models.CharField(max_length=50)                               # 公开（公告）号
    pub_time = models.CharField(max_length=50,null=True)                    # 公开（公告）日期
    proposer = models.CharField(max_length=50, null=True)                   # 申请（专利权）人
    inventor = models.CharField(max_length=250, null=True)                  # 发明（设计）人
    proposer_addr = models.CharField(max_length=500, null=True)             # 申请人地址
    ipc_classifi = models.CharField(max_length=2000, null=True)             # IPC分类号
    patent_abs = models.TextField(null=True)                                # 摘要内容
    lang = models.CharField(max_length=30, null=True)                       # 所属语言
    legel_status = models.CharField(max_length=1000, null=True)             # 法律状态
    priority_num = models.CharField(max_length=1000, null=True)             # 优先权号
    priority_time = models.CharField(max_length=100,null=True)              # 优先权日

    class Meta:
        db_table = 'patent_info'                                            # 给表起的别名，数据库中显示的是该名字

    def add(self):
        return {'patent_Id':self.patent_Id, 'patent_name':self.patent_name, 'appli_num':self.appli_num,
                'appli_time':self.appli_time, 'pub_num ':self.pub_num , 'pub_time':self.pub_time,
                'proposer':self.proposer,'inventor':self.inventor,'proposer_addr':self.proposer_addr,
                'ipc_classifi':self.ipc_classifi,'legel_status':self.legel_status}

# 详细信息表
class PatentOtherInfo(models.Model):
    appli_num = models.CharField(max_length=50)                             # 申请号
    locarno_class = models.CharField(max_length=100, null=True)             # 洛迦诺分类
    intl_appli_data = models.CharField(max_length=100, null=True)           # 国际申请
    intl_pub_time = models.CharField(max_length=50, null=True)              # 国际公布
    entry_state_date = models.CharField(max_length=100,null=True)           # 进入国家日期
    keyword = models.CharField(max_length=1000, null=True)                  # 关键词
    cpc_classifi = models.CharField(max_length=2000, null=True)             # CPC分类号
    proposer_code = models.CharField(max_length=50,null=True)               # 申请人邮编
    angency = models.CharField(max_length=1000, null=True)                  # 代理机构
    angent = models.CharField(max_length=200, null=True)                    # 代理人
    patent_claims = models.TextField(null= True)                            # 权利要求书
    instructions = models.TextField(null=True)                              # 说明书
    abstract_image_path = models.TextField(max_length=700, null=True)       # 说明书附图路径
    patent_text_path = models.CharField(max_length=700, null=True)          # PDF文本路径
    law_time = models.CharField(max_length=100,null=True)                   # 法律最后生效时间
    patent_info = models.OneToOneField(PatentInfo,on_delete=models.CASCADE) # 和主信息建立一对一的关系

    class Meta:
        db_table = 'second_info'


# 法律状态表
class LawStatus(models.Model):
    law_effective_date = models.CharField(max_length=50,null=True)            # 法律状态生效日
    law_meaning = models.CharField(max_length=300,null=True)                  # 法律状态含义
    patent_info = models.ForeignKey(PatentInfo,on_delete=models.CASCADE)      # 和主信息建立一对多的关系（即一个专利对应多个法律状态）

    class Meta:
        db_table = 'law_info'


# 相关性表
class Reference(models.Model):
    id = models.AutoField(primary_key=True)                                     # 主键自动增加
    appli_num = models.CharField(max_length=50)                                 # 公开号（唯一）
    other_appli_num = models.CharField(max_length=50,null=True)                 # 相关专利的申请号
    other_pub_num = models.CharField(max_length=50,null=True)                   # 其他相关专利的公开号
    other_title = models.CharField(max_length=200,null=True)                    # 其他专利的名字
    correlate = models.CharField(max_length=20,null=True)                       # 专利之间关系（引证，被引，同族）
    patent_info = models.ForeignKey(PatentInfo,on_delete=models.CASCADE)        # 和主表建立一对多的关系

    class Meta:
        db_table = 'relate_info'

sitesearch/views.py
#coding=UTF-8
from django.http import HttpResponse
from elasticsearch import Elasticsearch
import json
client = Elasticsearch(hosts=["127.0.0.1"])
from datetime import datetime
from . import base_search
from . import test_search
from .models import PatentInfo
from .models import PatentOtherInfo
from .models import LawStatus
from .models import Reference
from django.core import serializers
from django.shortcuts import render,HttpResponse
import ast
import xlwt
from datetime import time
# Create your views here.

def index(request):
    return render(request, 'sitesearch/index.html')

# 根据关键词到数据库中查询相关数据并返回结果界面
def word_search(request):
    try:
        # 获取普通搜索关键词
        key_words = request.GET.get('q', '')    # 获取到请求词
        page = request.GET.get('p', '1')        # 获取访问页码
        num = request.GET.get('n', '10')          # 获取每页显示数量
        order = request.GET.get('o', 'default')        # 获取排序方式
        f = request.GET.get('f', '0')                # 前台显示方式
        f_flag = request.GET.get('f_flag', '0')      # 高级搜索标志
        print("keywords"+key_words)
        print("f:"+f)

        # 获取高级搜索关键词
        final_words = {}
        appli_num = request.GET.get('appli_num', '')  # 申请号
        appli_time = request.GET.get('appli_time', '')  # 申请日
        patent_name = request.GET.get('patent_name', '')  # 名称
        pub_num = request.GET.get('pub_num', '')  # 公开号
        pub_time = request.GET.get('pub_time', '')  # 公开日
        # cpc_classifi = request.GET.get('cpc_classifi', '')  # cpc分类号
        ipc_classifi = request.GET.get('ipc_classifi', '')  # ipc分类号
        proposer = request.GET.get('proposer', '')  # 申请人
        inventor = request.GET.get('inventor', '')  # 发明人
        # angent = request.GET.get('angent', '')  # 代理人
        # angency = request.GET.get('angency', '')  # 代理机构
        # patent_type = request.GET.get('patent_type', '')  # 专利类型
        final_words["SQH"] = appli_num
        final_words["GKH"] = pub_num
        final_words["ZLMC"] = patent_name
        # final_words["CPC"] = cpc_classifi
        final_words["IPC"] = ipc_classifi
        final_words["SQR"] = proposer
        # final_words["DLR"] = angent
        final_words["SQSJ"] = appli_time
        final_words["GKSJ"] = pub_time
        final_words["FMR"] = inventor
        # final_words["DLJG"] = angency
        # final_words["ZLLX"] = patent_type
        print("final_words1"+str(final_words))

        if f_flag == '2':
            final_words = ast.literal_eval(key_words)
            print("fin_words2"+str(final_words))
        elif f_flag == '1':
            f_flag = '2'
            final_words["SSC"] = key_words


        # 结果筛选
        filter_words = {}
        key_words2 = request.GET.get('key_words2', '')      # 搜索条款关键词
        search_date = request.GET.get('search_date', '')        # 筛选条款日期
        begin_date = request.GET.get('begin_date', '')          # 开始日期
        end_date = request.GET.get('end_date', '')              # 结束日期
        language = request.GET.get('language', '')              # 专利语言
        # patent_type = request.GET.get('patent_type', '')        # 专利类型
        legal_status = request.GET.get('legal_status', '')      # 专利法律状态
        filter_words["SSC"] = key_words2
        filter_words["SSRQ"] = search_date
        filter_words["QSRQ"] = begin_date
        filter_words["JSRQ"] = end_date
        filter_words["ZLYY"] = language
        # filter_words["ZLLX"] = patent_type
        filter_words["FLZT"] = legal_status
        print(filter_words)

        fil_flag = '0'
        for m in filter_words:
            if filter_words[m]:
                fil_flag = '1'
        print("f_flag:"+str(f_flag))
        print("fil_flag:"+str(fil_flag))
        try:
            page = int(page)
        except:
            page = 1
        try:
            num = int(num)
        except:
            num = 10
        test = False
        if (not key_words) and (f_flag == '0'):     # 若搜索栏为空，返回主页
            return render(request, 'sitesearch/index.html')
        else:
            if test == True:
                search_result = test_search.main(key_words, page, num, order, final_words, filter_words, f_flag, fil_flag)
            else:
                search_result = base_search.main(key_words, page, num, order, final_words, filter_words, f_flag, fil_flag)
            return render(request, 'sitesearch/patent_list.html',
                          {"search_result": search_result["last_result"],       # 数据列表
                           "key_words": search_result["key_words"],             # 搜索关键词
                           "filter_words": filter_words,                         # 筛选词
                           "page": search_result["page"],                       # 当前页码
                           "total_nums": search_result["total_nums"],           # 数据总条数
                           "page_nums": search_result["page_nums"],             # 页数
                           "last_time": search_result["last_time"],             # 搜索时间
                           "front": search_result["front"],                     # 是否有上一页
                           "after": search_result["after"],                     # 是否有下一页
                           #"ssc": final_words["SSC"],                            # 高级搜索搜索词
                           "f": f,                                              # 前台显示方式
                           "o": order,
                           "n": num,                                            # 每页显示数量
                           "f_flag": f_flag,                                     # 高级搜索标志
                           "invcount_result": search_result["invcount"],        # 发明人统计结果
                           "ipccount_result": search_result["ipccount"],        # IPC分类号统计结果
                           "procount_result": search_result["procount"],        # 申请人统计结果

                           })                                                   # 显示页面和将列表和搜索词返回到html

    except Exception as e:
        print(e)
        response = HttpResponse(json.dumps({"msg": e}), content_type='application/json')
        response['Access-Control-Allow-Origin'] = '*'
        return response

# 查看专利完整信息
def detail(request):
    try:
        print("detailstart")
        q = request.GET.get('q')
        print(q)
        patent_info_search = PatentInfo.objects.filter(patent_Id=q)
        patentotherinfo_search = PatentOtherInfo.objects.filter(patent_info=q)
        lawstatus_search = LawStatus.objects.filter(patent_info=q)
        reference_search = Reference.objects.filter(patent_info=q)
        patent_info_trans = json.loads(serializers.serialize("json", patent_info_search))
        patentotherinfo_trans = json.loads(serializers.serialize("json", patentotherinfo_search))
        lawstatus_trans = json.loads(serializers.serialize("json", lawstatus_search))
        reference_trans = json.loads(serializers.serialize("json", reference_search))
        for n in lawstatus_trans:
            m1 = n['fields']['law_effective_date']
            m2 = m1[0:4]+'.'+m1[4:6]+'.'+m1[6:]
            n['fields']['law_effective_date'] = m2
        # print(lawstatus_trans)
        print("detailend")
        return render(request, 'sitesearch/detail.html', {'patent_info': patent_info_trans,
                                                          'patentotherinfo': patentotherinfo_trans,
                                                          'lawstatus': lawstatus_trans,
                                                          'reference': reference_trans})
    except Exception as e:
        print(e)
        response = HttpResponse(json.dumps({"msg": e}), content_type='application/json')
        response['Access-Control-Allow-Origin'] = '*'
        return response

# 专利收藏
def collect(request):
    try:
        patent_id = request.POST.get('patent_id','')
        # 获取要放入购物车中的商品信息
        if patent_id:
            patent_search = PatentInfo.objects.get(patent_Id=patent_id)
            collect = patent_search.add()
            # 从session获取购物车信息，没有默认空字典
            collectlist = request.session.get('collectlist', {})
            # 判断此商品是否在购物车中
            if patent_id in collectlist:
                # 取消收藏
                del collectlist[patent_id]
            else:
                # 建立新收藏
                collectlist[patent_id] = collect
        else:
            collectlist = request.session.get('collectlist', {})
        # 将购物车信息放回到session
        request.session['collectlist'] = collectlist
        print(collectlist)
        return HttpResponse(json.dumps(collectlist))
    except Exception as e:
        print(e)
        response = HttpResponse(json.dumps({"msg": e}), content_type='application/json')
        response['Access-Control-Allow-Origin'] = '*'
        return response

# 获取收藏夹
def collection(request):
    try:
        collectlist = request.session.get('collectlist', {})
        print(collectlist)
        return render(request, "sitesearch/collection.html", locals())
    except Exception as e:
        print(e)
        response = HttpResponse(json.dumps({"msg": e}), content_type='application/json')
        response['Access-Control-Allow-Origin'] = '*'
        return response
    return render(request, "sitesearch/collection.html")

# 导出Excel
def excel_export(request):
    try:
        patent_list = request.POST.getlist('patent_list')
        print("test")
        print(patent_list)
        # patent_list = ['CN201610482669.820180105FM','CN201610490172.020160914FM','CN201610505659.120180109FM',
        #                'CN201610539890.220161207FM','CN201610552692.X20161207FM','CN201610350337.420171201FM',
        #                'CN201610597401.920180202FM','CN201610388003.620171212FM']
        print(type(patent_list))
        response = HttpResponse(content_type='application/vnd.ms-excel')
        response['Content-Disposition'] = 'attachment; filename=download.xls'
        
        workbook = xlwt.Workbook(encoding='utf-8')  # 创建工作簿

sitesearch/templates/sitesearch/collection.html
{% extends 'law_regulate/base.html' %}
{% load filtrate %}
{% load staticfiles %}
{% block topsearch %}
    <div class="topSearch">
        <form method="GET" action="{% url 'sitesearch:word_search' %}" id="searchForm">
            <input type="text" placeholder="请输入查询关键词" class="form-control" name="q" value="{{key_words}}"  autocomplete="off">
            <input type="text" name="f" value="{{f}}" style="display: none;">
            <input type="text" name="f_flag" value="0" style="display: none;">
            <a href="javascript:" onclick="document.getElementById('searchForm').submit();return false;"><i class="fa fa-search"></i></a>
            <button type="submit" style="display: none;"></button>
        </form>
    </div>
{% endblock %}
<!--收藏夹主页-->
<!--与之前的Patent_list.html 里面表格式页面一样-->
{% block collection %}
<div class="wrapZCont" style="margin-left: 80px;">
    <div class="container-fluid margin-t50">
        <div class="col-sm-1"></div>
        <div class="col-sm-10">
            <div id="changed-form" class="search-pane">
                <div class="yzTable">
                    <table>
                        <thead>
                            <tr>
                                <th>序号</th>
                                <th class="lawStatus">法律状态</th>
                                <th class="w200">专利名称</th>
                                <th>申请号</th>
                                <th>申请人</th>
                                <th>发明人</th>
                                <th>申请日</th>
                                <th>分类号</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody id="star_flag">
                        
                        </tbody>
                    </table>
                    <form action="{% url 'sitesearch:excel_export' %}" method="POST" id="starArrayExcel" style="display: none;">{% csrf_token %}
                        <button type="submit">submit</button>
                    </form>
                    <div class="col-sm-1 excel-button"> 
                        <button id="excel-button" type="button" class="col-sm-12 ex-button"> <i class="fa fa-file" aria-hidden="true"></i>&nbsp;&nbsp;导出</button>
                    </div>    
                </div>
                <!--分页-->
                {% if search_result %}
                <div class="pages mt20">
                    <a href="word_search?q={{key_words}}&p=1&n={{n}}&{{o}}&key_words2={{filter_words.SSC}}&search_date={{filter_words.SSRQ}}&begin_date={{filter_words.QSRQ}}&end_date={{filter_words.JSRQ}}&language={{filter_words.ZLYY}}&legal_status={{filter_words.FLZT}}&f_flag={{f_flag}}&f=1">首页</a>
                    {% if front %}
                    <a href="word_search?q={{key_words}}&p={{page|add:-1}}&n={{n}}&{{o}}&key_words2={{filter_words.SSC}}&search_date={{filter_words.SSRQ}}&begin_date={{filter_words.QSRQ}}&end_date={{filter_words.JSRQ}}&language={{filter_words.ZLYY}}&legal_status={{filter_words.FLZT}}&f_flag={{f_flag}}&f=1"><i class="fa fa-angle-left mr_5"></i>上一页</a>
                    {% endif %}
                    <a class="localPage" style="display: none;"></a>
                    {% if after %}
                    <a href="word_search?q={{key_words}}&p={{page|add:+1}}&n={{n}}&{{o}}&key_words2={{filter_words.SSC}}&search_date={{filter_words.SSRQ}}&begin_date={{filter_words.QSRQ}}&end_date={{filter_words.JSRQ}}&language={{filter_words.ZLYY}}&legal_status={{filter_words.FLZT}}&f_flag={{f_flag}}&f=1">下一页<i class="fa fa-angle-right ml_5"></i></a>
                    {% endif %}
                </div>
                {% endif %}
            </div>
        </div>
        <div class="col-sm-1"></div>
    </div>
</div>

<script>
    var starArray=new Array();
    /**
     * 通过Ajax获取 被收藏专利的信息
    */
    $.ajax({  
            url: "{% url 'sitesearch:collect' %}", 
            type: 'POST', 
            dataType: 'json',  
            success:function(data){
                jQuery.each(data,function (index,element) {
                    starArray.push(index)  
                })
                let i=1;
                for(name in data){//循环出列表
                    var n=document.getElementsByClassName(name);
                    $(n).removeClass("fa-star-o");
                    $(n).addClass("fa-star");
                    let list="<tr>"+
                             "<td class=list-number>"+i+"</td>"+
                             "<td class=\"lawStatus\">"+
                             "<span class=\"badge badge-primary badge_big\">"+
                             data[name].legel_status+
                             "   </span>"+
                             "</td>"+
                             "<td id=\"patent-name-color\">"+
                             "   <span class=\"lawAdd\">"+
                             "      <span class=\"badge badge-primary badge_big mr5\">"+
                             "       </span>"+
                             "   </span>"+
                             "   <a href=\"detail?q="+data[name].patent_Id+"\">"+data[name].patent_name+"</a>"+
                             "</td>"+
                            "<td>"+data[name].appli_num+"</td>"+
                            "<td>"+data[name].proposer+"</td>"+
                            "<td>"+data[name].inventor+"</td>"+
                            "<td>"+data[name].appli_time+"</td>"+
                            "<td>"+data[name].ipc_classifi+"</td>"+
                            "<td>"+
                            "    <a href=\"javascript:void(0)\" onclick=\"starSubmit('"+data[name].patent_Id+"')\"class=\"fc_default mlr5\"><i class=\"fa fa-star fs_20 "+ data[name].patent_Id+"\"></i></a>"+
                            "    <a href=\"javascript:void(0)\" class=\"fc_default mlr5\"><i class=\"fa fa-download fs_20\"></i></a>"+
                            "</td>"+
                            "</tr>";
                    $("#star_flag").append(list);
                    i++;
                }
                console.log(data[name]);
            },
            error:function(request, errorType, errorMessage){
                console.log(request);
                console.log(errorType);
                console.log(errorMessage);
            }
        })
        /*
        *提交收藏专利 的信息功能
        */
        function starSubmit(patentId) {
            var ptI=document.getElementById(patentId);
            $.ajax({  
            url: "{% url 'sitesearch:collect' %}", 
            type: 'POST', 
            data: {
                'patent_id':patentId,
            }, 
            dataType: 'json',  
            success:function(data){
                let star=document.getElementsByClassName(patentId);
                if(data[patentId]){
                    $(star).removeClass("fa-star-o");
                    $(star).addClass("fa-star");
                }
                else{
                    $(star).removeClass("fa-star");
                    $(star).addClass("fa-star-o");
                }
     
            },
            error:function(request, errorType, errorMessage) {
                console.log(request);
                console.log(errorType);
                console.log(errorMessage);
            }
        })
        }
        /*导航栏里的 收藏功能*/
        function clickList() {
            $("#starList").empty();
            let i=0;
            $.ajax({  
            url: "{% url 'sitesearch:collect' %}", 
            dataType: 'json',
            type: 'POST',
            data: {
                'patent_id':'',
            },  
            success:function(data){                
                for(name in data){
                    let starList="<li><a  href=\"detail?q="+name+"\">"+data[name].patent_name+" "+data[name].appli_num+"</a></li>";
                    let more="<li id=\"excel_more\"><span class=\"excel-left\"><a href=\"javascript:void(0);\" onclick=\"excelExport()\">导出</a></span> <span class=\"more-right\"><a href=\"/collection\">查看全部</a></span> </li>";
                    $("#starList").append(starList);
                }
                let more="<li id=\"excel_more\"><span class=\"excel-left\"><a href=\"javascript:void(0);\" onclick=\"excelExport()\">导出</a></span> <span class=\"more-right\"><a href=\"/collection\">查看全部</a></span> </li>";
                $("#starList").append(more);
                
            },
            error:function(request, errorType, errorMessage) {
                console.log(request);
                console.log(errorType);
                console.log(errorMessage);
            }
        })
        }
        /*Excel 导出*/
        $("#excel-button").click(function () {
            
            for(list in starArray){
                let starlist="<input type=\"text\" name=\"patent_list\" value="+starArray[list]+">";
                $("#starArrayExcel").append(starlist);
            }
            $("#starArrayExcel").submit();
        
            
        })
        

</script>
{% endblock %}

sitesearch/templates/sitesearch/index.html
{% extends 'law_regulate/base.html' %}
{% load staticfiles %}
{% block background-birds %}
<!--Canvas-->
<div class="bg">
    <div id="birds-canvas-holder"></div>
</div>
<script type="text/javascript" src="{% static 'sitesearch/js/three.min.js' %}"></script>
<script type="text/javascript" src="{% static 'sitesearch/js/renderers/Projector.js' %}"></script>
<script type="text/javascript" src="{% static 'sitesearch/js/renderers/CanvasRenderer.js' %}"></script>
<script type="text/javascript" src="{% static 'sitesearch/js/birds.js' %}"></script>
<script type="text/javascript" src="{% static 'sitesearch/js/renderers/TWeenMax.js' %}"></script>
{% endblock %}
<!--logo-->
<!--搜索框-->
{% block searchBar %}
<div class="container container-s">
    <div class="row row-s row-centered">
      <div class="col-md-10 col-md-offset-1 trans height-30">
        <div class="col-md-12 col-centered index-logo">
            <img src="{% static 'sitesearch/img/logo_sm.png' %}" class="img-responsive" alt="Responsive image">
        </div>
        <div class="col-md-12  col-sm-8 col-xs-8 col-centered bg-w">
            <form class="" role="search" method="GET" action="{% url 'sitesearch:word_search' %}" id="indexSearch">
                <div>
                    <input  type="text"  class="form-control input-lg" name="q" placeholder="搜索专利" id="searchDate"  autocomplete="off"/>
                </div>
                <a href="javascript:" name="submit" onclick="$('#indexSearch').submit();return false;" class="index-s"><i class="fa fa-search fa-2x"></i></a>
            </form>
            <a class="" id="adv-search" >高级搜索  <i class="fa fa-sort-desc fa-lg lineh-4" aria-hidden="true" id="adv-logo"></i></a>
            <form role="search" method="GET" action="{% url 'sitesearch:word_search' %}" id="indexsearch" class="form-group row">
                <div class="advanced-search">
                    <div class="col-md-12"><input class="col-md-3" type="text" placeholder="申请号" name="appli_num"  autocomplete="off"><input class="col-md-3" type="text" placeholder="申请日" name="appli_time"  autocomplete="off"><input class="col-md-3" type="text" placeholder="名称" name="patent_name"  autocomplete="off"></div>
                    <div class="col-md-12"><input class="col-md-3" type="text" placeholder="公开号" name="pub_num"  autocomplete="off"><input class="col-md-3" type="text" placeholder="公开日" name="pub_time"  autocomplete="off"><input class="col-md-3" type="text" placeholder="CPC分类号" name="cpc_classifi" disabled="disabled"  autocomplete="off"></div>
                    <div class="col-md-12"><input class="col-md-3" type="text" placeholder="IPC分类号"  name="ipc_classifi"  autocomplete="off"><input class="col-md-3" type="text" placeholder="申请人" name="proposer"  autocomplete="off"><input class="col-md-3" type="text" placeholder="发明人" name="inventor"  autocomplete="off"></div>
                    <div class="col-md-12"><input class="col-md-3" type="text" placeholder="代理人" disabled="disabled" name="angent"  autocomplete="off"><input class="col-md-3" type="text" placeholder="代理机构" disabled="disabled" name="angency"  autocomplete="off"><input class="col-md-3" type="text" placeholder="专利类型" disabled="disabled" name="patent_type"  autocomplete="off"></div>
                    <div class="col-md-12"><input class="col-md-3" type="text" name="f_flag" value="0" style="display: none;" id="hiddenfg"></div>
                    <div class="col-md-2 mrl-617"><button type="reset" class="adv-reset col-md-10" style="color: #999;margin-left: 40px;border-radius: 20px;">RESET</button></div>
                    <div class="col-md-2"><button  type="submit" class="adv-submit col-md-10" style="color: white;margin-left: 30px; border-radius: 20px;" id="adv-submit">SUBMIT</a></div>
                </div>
            </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}
{% block foot %}
<footer id="footer" style="position:absolute; bottom:0;">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p><span><a href="#">联系我们</a></span>|<span><a href="#">免责申明</a></span></p>
                <p><foot>©2003-2017 SooPAT</foot> <a href="#">苏ICP备11038928号-2</a> <foot>苏公网安备 32059002001550号</foot></p>
            </div>
        </div>
    </div>
</footer>
{% endblock %}