PatentMiner/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('sitesearch.urls',namespace="sitesearch")),
    url(r'^law_regulate/', include('law_regulate.urls',namespace="law_regulate")),
]

law_regulate/urls.py
from django.conf.urls import url

from . import views

app_name = 'law_regulate'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^law_index$', views.law_index, name='law_index'),
    url(r'^law_detail$', views.law_detail, name='law_detail'),
    url(r'^law_search$', views.law_search, name='law_search'),

]

sitesearch/urls.py
from django.conf.urls import url

from . import views

app_name = 'law_regulate'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^word_search$', views.word_search, name='word_search'),
    url(r'^detail$', views.detail, name='detail'),
    url(r'^collect$', views.collect, name='collect'),
    url(r'^collection$', views.collection, name='collection'),
    url(r'^excel_export$', views.excel_export, name='excel_export'),

]

law_regulate/models.py
from django.db import models

# Create your models here.

"""
法律法规的数据库
"""


class LawRegulate(models.Model):
    law_id = models.CharField(max_length=10,null=True)              # 每个json文件里id标识
    category = models.CharField(max_length=100,null=True)           # 法律的类别
    law_title = models.CharField(max_length=150,null=True)          # 法律标题
    publish_time = models.CharField(max_length=20,null=True)        # 颁布时间
    effect_time = models.CharField(max_length=20,null=True)      # 生效时间
    content = models.TextField(null=True)                           # 法律内容
    json_tile = models.CharField(max_length=35,null=True)           # 所属的那个json文件名

    class Meta:
        db_table = 'regulate_info'

law_regulate/views.py
#coding=UTF-8
# Create your views here.
from .models import LawRegulate
import json
from django.core import serializers
from django.shortcuts import render, HttpResponse
from django.db.models import Q

def index(request):
    return render(request, 'sitesearch/index.html')

def law_index(request):
    try:
        print("lawstart")
        # 反垄断法
        antitrust_list = {}
        antilaw_search = LawRegulate.objects.filter(Q(json_tile='antitrust_law.json') & Q(category='法律'))
        antilaw_information = json.loads(serializers.serialize("json", antilaw_search))
        a = []
        for n in antilaw_information:
            b = {}
            b["id"] = n["fields"]["law_id"]
            b["category"] = n["fields"]["category"]
            b["law_title"] = n["fields"]["law_title"]
            b["json_tile"] = n["fields"]["json_tile"]
            b["publish_time"] = n["fields"]["publish_time"]
            b["effect_time"] = n["fields"]["effect_time"]
            a.append(b)
        antitrust_list["law"] = a

        a = []
        antistate_search = LawRegulate.objects.filter(Q(json_tile='antitrust_law.json') & Q(category='国务院部门规章'))
        antistate_information = json.loads(serializers.serialize("json", antistate_search))
        for n in antistate_information:
            b = {}
            b["id"] = n["fields"]["law_id"]
            b["category"] = n["fields"]["category"]
            b["law_title"] = n["fields"]["law_title"]
            b["json_tile"] = n["fields"]["json_tile"]
            b["publish_time"] = n["fields"]["publish_time"]
            b["effect_time"] = n["fields"]["effect_time"]
            a.append(b)
        antitrust_list["state"] = a

        # 著作权
        copyright_list = {}
        copylaw_search = LawRegulate.objects.filter(Q(json_tile='copyright_law.json') & Q(category='法律'))
        copylaw_information = json.loads(serializers.serialize("json", copylaw_search))
        a = []
        for n in copylaw_information:
            b = {}
            b["id"] = n["fields"]["law_id"]
            b["category"] = n["fields"]["category"]
            b["law_title"] = n["fields"]["law_title"]
            b["json_tile"] = n["fields"]["json_tile"]
            b["publish_time"] = n["fields"]["publish_time"]
            b["effect_time"] = n["fields"]["effect_time"]
            a.append(b)
        copyright_list["law"] = a

        a = []
        copyadmin_search = LawRegulate.objects.filter(Q(json_tile='copyright_law.json') & Q(category='行政法规'))
        copyadmin_information = json.loads(serializers.serialize("json", copyadmin_search))
        for n in copyadmin_information:
            b = {}
            b["id"] = n["fields"]["law_id"]
            b["category"] = n["fields"]["category"]
            b["law_title"] = n["fields"]["law_title"]
            b["json_tile"] = n["fields"]["json_tile"]
            b["publish_time"] = n["fields"]["publish_time"]
            b["effect_time"] = n["fields"]["effect_time"]
            a.append(b)
        copyright_list["admin"] = a

        a = []
        copystate_search = LawRegulate.objects.filter(Q(json_tile='copyright_law.json') & Q(category='国务院部门规章'))
        copystate_information = json.loads(serializers.serialize("json", copystate_search))
        for n in copystate_information:
            b = {}
            b["id"] = n["fields"]["law_id"]
            b["category"] = n["fields"]["category"]
            b["law_title"] = n["fields"]["law_title"]
            b["json_tile"] = n["fields"]["json_tile"]
            b["publish_time"] = n["fields"]["publish_time"]
            b["effect_time"] = n["fields"]["effect_time"]
            a.append(b)
        copyright_list["state"] = a

        a = []
        copyregul_search = LawRegulate.objects.filter(Q(json_tile='copyright_law.json') & Q(category='地方性法规'))
        copyregul_information = json.loads(serializers.serialize("json", copyregul_search))
        for n in copyregul_information:
            b = {}
            b["id"] = n["fields"]["law_id"]
            b["category"] = n["fields"]["category"]
            b["law_title"] = n["fields"]["law_title"]
            b["json_tile"] = n["fields"]["json_tile"]
            b["publish_time"] = n["fields"]["publish_time"]
            b["effect_time"] = n["fields"]["effect_time"]
            a.append(b)
        copyright_list["regulations"] = a

        a = []
        copyregul_search = LawRegulate.objects.filter(Q(json_tile='copyright_law.json') & Q(category='地方政府规章'))
        copyregul_information = json.loads(serializers.serialize("json", copyregul_search))
        for n in copyregul_information:
            b = {}
            b["id"] = n["fields"]["law_id"]
            b["category"] = n["fields"]["category"]
            b["law_title"] = n["fields"]["law_title"]
            b["json_tile"] = n["fields"]["json_tile"]
            b["publish_time"] = n["fields"]["publish_time"]
            b["effect_time"] = n["fields"]["effect_time"]
            a.append(b)
        copyright_list["govregulations"] = a


        # 域名法
        domain_list = {}
        domainstate_search = LawRegulate.objects.filter(Q(json_tile='domain_name_law.json') & Q(category='国务院部门规章'))
        domainstate_information = json.loads(serializers.serialize("json", domainstate_search))
        a = []
        for n in domainstate_information:
            b = {}
            b["id"] = n["fields"]["law_id"]
            b["category"] = n["fields"]["category"]
            b["law_title"] = n["fields"]["law_title"]
            b["json_tile"] = n["fields"]["json_tile"]
            b["publish_time"] = n["fields"]["publish_time"]
            b["effect_time"] = n["fields"]["effect_time"]
            a.append(b)
        domain_list["state"] = a


        # 地理标志法
        geographical_list = {}
        geographicalstate_search = LawRegulate.objects.filter(Q(json_tile='geographical_indication_law.json') & Q(category='国务院部门规章'))
        geographicalstate_information = json.loads(serializers.serialize("json", geographicalstate_search))
        a = []
        for n in geographicalstate_information:
            b = {}
            b["id"] = n["fields"]["law_id"]
            b["category"] = n["fields"]["category"]
            b["law_title"] = n["fields"]["law_title"]
            b["json_tile"] = n["fields"]["json_tile"]
            b["publish_time"] = n["fields"]["publish_time"]
            b["effect_time"] = n["fields"]["effect_time"]
            a.append(b)
        geographical_list["state"] = a


        # 集成电路法
        integrated_list = {}
        integratedstate_search = LawRegulate.objects.filter(Q(json_tile='integrated_circuit_law.json') & Q(category='国务院部门规章'))
        integratedstate_information = json.loads(serializers.serialize("json", integratedstate_search))
        a = []
        for n in integratedstate_information:
            b = {}
            b["id"] = n["fields"]["law_id"]
            b["category"] = n["fields"]["category"]
            b["law_title"] = n["fields"]["law_title"]
            b["json_tile"] = n["fields"]["json_tile"]
            b["publish_time"] = n["fields"]["publish_time"]
            b["effect_time"] = n["fields"]["effect_time"]
            a.append(b)
        integrated_list["state"] = a

        # 植物新品种
        new_plant_list = {}

        a = []
        new_plantadmin_search = LawRegulate.objects.filter(Q(json_tile='new_plant_species_law.json') & Q(category='行政法规'))
        new_plantadmin_information = json.loads(serializers.serialize("json", new_plantadmin_search))
        for n in new_plantadmin_information:
            b = {}
            b["id"] = n["fields"]["law_id"]
            b["category"] = n["fields"]["category"]
            b["law_title"] = n["fields"]["law_title"]
            b["json_tile"] = n["fields"]["json_tile"]
            b["publish_time"] = n["fields"]["publish_time"]
            b["effect_time"] = n["fields"]["effect_time"]
            a.append(b)
        new_plant_list["admin"] = a

        a = []
        new_plantstate_search = LawRegulate.objects.filter(Q(json_tile='new_plant_species_law.json') & Q(category='国务院部门规章'))
        new_plantstate_information = json.loads(serializers.serialize("json", new_plantstate_search))
        for n in new_plantstate_information:
            b = {}
            b["id"] = n["fields"]["law_id"]
            b["category"] = n["fields"]["category"]
            b["law_title"] = n["fields"]["law_title"]
            b["json_tile"] = n["fields"]["json_tile"]
            b["publish_time"] = n["fields"]["publish_time"]
            b["effect_time"] = n["fields"]["effect_time"]
            a.append(b)
        new_plant_list["state"] = a

        a = []
        new_plantregul_search = LawRegulate.objects.filter(Q(json_tile='new_plant_species_law.json') & Q(category='地方性法规'))
        new_plantregul_information = json.loads(serializers.serialize("json", new_plantregul_search))
        for n in new_plantregul_information:
            b = {}
            b["id"] = n["fields"]["law_id"]
            b["category"] = n["fields"]["category"]
            b["law_title"] = n["fields"]["law_title"]
            b["json_tile"] = n["fields"]["json_tile"]
            b["publish_time"] = n["fields"]["publish_time"]
            b["effect_time"] = n["fields"]["effect_time"]
            a.append(b)
        new_plant_list["regulations"] = a

        # 专利法
        patent_list = {}
        patentlaw_search = LawRegulate.objects.filter(Q(json_tile='patent_law.json') & Q(category='法律'))
        patentlaw_information = json.loads(serializers.serialize("json", patentlaw_search))
        a = []
        for n in patentlaw_information:
            b = {}
            b["id"] = n["fields"]["law_id"]
            b["category"] = n["fields"]["category"]
            b["law_title"] = n["fields"]["law_title"]
            b["json_tile"] = n["fields"]["json_tile"]
            b["publish_time"] = n["fields"]["publish_time"]
            b["effect_time"] = n["fields"]["effect_time"]

law_regulate/templates/law_regulate/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=0.1, maximum-scale=1.0 initial-scale=0.28">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">   
    <link rel="stylesheet" href="{% static 'sitesearch/css/old/reset.css' %}">
    <link rel="stylesheet" href="{% static 'sitesearch/css/old/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'sitesearch/css/old/patent_list.css' %}">
    <link rel="stylesheet" href="{% static 'sitesearch/css/old/index.css' %}">
    <script type="text/javascript" src="{% static 'sitesearch/js/jquery.min.js' %}"></script>
    <script src="{% static 'sitesearch/js/new/jqajax.js' %}"></script>
    <!--新的页面css导入-->
    <link rel="stylesheet" href="{% static 'sitesearch/css/bootstrap.min14ed.css' %}">
    <link rel="stylesheet" href="{% static 'sitesearch/css/font-awesome.min93e3.css' %}">
    <link rel="stylesheet" href="{% static 'sitesearch/css/style.min862f.css' %}">
    <link rel="stylesheet" href="{% static 'sitesearch/css/common-new.css' %}">
    <link rel="stylesheet" href="{% static 'sitesearch/css/animate.css' %}">
    <title>PatentMiner专利搜索</title>
    <style>
    </style>
</head>
<body class="gray-bg pt72">
<!-- 导航栏 -->
<!--顶部模块-->
<div class="headbox c">
    <div class="top-padd pull-left">
        <div class="toplogo">
            <a href="/"><img src="{% static 'sitesearch/img/logo_sm.png' %}" alt="首页"></a>
        </div>
        {% block topsearch %}{% endblock %}
        <ul class="topMenu" id="side-menu">
            <!-- <li>
                <a href="index.html" class="J_menuItem">
                    <span class="nav-label">高级搜索</span>
                </a>
            </li> -->
            <li>
                <a href="/law_regulate/law_index" class="J_menuItem">
                    <span class="nav-label">法规页面</span>
                </a>
            </li>
        </ul>
    </div>
    <!--
    <ul class="language">
        <li class="active">
            <a href="###">中文</a>
        </li>
        <li>
           <a href="###">English</a>
        </li>
    </ul>
    
    <div class="line"></div>
    -->
    <!-- <div class="menubar">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <ul class="right_nar">
                    <li class="nav_first">
                        <a href="javascript:void(0);" class="admininfo">
                            <img class="img-circle mr_5" src="{% static 'sitesearch/img/head.png' %}" width="40" height="40"/>
                            <p>Admin</p>
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="javascript:void(0);">基本信息</a></li>
                            <li><a href="javascript:void(0);">后台管理</a></li>
                            <li><a  href="javascript:void(0);">切换用户</a></li>
                            <li><a  href="javascript:void(0);">退出登录</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </div> -->
<div class="menubar">
    <nav class="navbar navbar-default fl-left">
        <div class="container-fluid">
            <ul class="right_nar">
                <li class="nav_first">
                    <a href="javascript:void(0);" class="admininfo lineh-28" onclick="clickList()">
                        <i class="fa fa-bell fa-1x" aria-hidden="true"></i>
                        <p>收藏列表</p>
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" id="starList">
                        
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</div>
</div> 
{% block collection %}{% endblock %}
{% block whitespace %}{% endblock %}
{% block logo %}{% endblock %}
{% block searchBar %}{% endblock %}
{% block advanced_search %}{% endblock %}
{% block sidebar %}{% endblock %}
{% block tablist %}{% endblock %}
{% block background-birds %}{% endblock %}
{% block ajax %}{% endblock %}
{% block detail%}{% endblock %}



<script type="text/javascript" src="{% static 'sitesearch/js/self_adaptation.js' %}"></script>
<!--新的js文件导入-->
<script src="{% static 'sitesearch/js/new/jquery.min.js' %}"></script>
<script src="{% static 'sitesearch/js/new/jquery.min2.js' %}"></script>
<script src="{% static 'sitesearch/js/new/jqajax.js' %}"></script>
<script src="{% static 'sitesearch/js/bootstrap.min.js' %}"></script>
<script src="{% static 'sitesearch/js/new/echarts-all.js' %}"></script>
<script src="{% static 'sitesearch/js/new/macarons.js' %}"></script>
<script src="{% static 'sitesearch/js/new/laydate/laydate.js' %}"></script>
<script src="{% static 'sitesearch/js/new/common.js' %}"></script>
<script src="{% static 'sitesearch/js/new/jquery-ui.min.js' %}"></script>
<script src="{% static 'sitesearch/js/new/esl.js' %}"></script>
<script src="{% static 'sitesearch/js/new/select-widget-min.js' %}"></script>

{% block js %}{% endblock %}
{% block laws%}{% endblock %}
{% block laws_details %}{%endblock%}
{% block form_page %}{% endblock %}
{% block foot %}
<footer id="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p><span><a href="#">联系我们</a></span>|<span><a href="#">免责申明</a></span></p>
                <p><foot>©2003-2017 SooPAT</foot> <a href="#">苏ICP备11038928号-2</a> <foot>苏公网安备 32059002001550号</foot></p>
            </div>
        </div>
    </div>
</footer>
{% endblock %}
{% block clickList %}
<script>
    /*该代码不要改，这是Jquery，AJax与Django接通时候，可能碰到BUG的解决办法*/
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie != '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) == (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        
        var csrftoken = getCookie('csrftoken');
        
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        
        function sameOrigin(url) {
            // test that a given url is a same-origin URL
            // url could be relative or scheme relative or absolute
            var host = document.location.host; // host + port
            var protocol = document.location.protocol;
            var sr_origin = '//' + host;
            var origin = protocol + sr_origin;
            // Allow absolute or scheme relative URLs to same origin
            return (url == origin || url.slice(0, origin.length + 1) == origin + '/') ||
                (url == sr_origin || url.slice(0, sr_origin.length + 1) == sr_origin + '/') ||
                // or any other URL that isn't scheme relative or absolute i.e relative.
                !(/^(\/\/|http:|https:).*/.test(url));
        }
        
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && sameOrigin(settings.url)) {
                    // Send the token to same-origin, relative URLs only.
                    // Send the token only if the method warrants CSRF protection
                    // Using the CSRFToken value acquired earlier
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        })
        /*获取收藏数据函数*/
        var starArray=new Array();
                    function clickList() {
                        $("#starList").empty();
                        let i=0;
                        $.ajax({  
                        url: "{% url 'sitesearch:collect' %}", 
                        dataType: 'json',
                        type: 'POST',
                        data: {
                            'patent_id':'',
                        },  
                        success:function(data){
                            console.log(data)
                            console.log(Object.keys(data).length)
                            jQuery.each(data,function (index,element) {
                                starArray.push(index)  
                            })
                            if(Object.keys(data).length){
                                for(name in data){
                                    let starList="<li><a  href=\"detail?q="+name+"\">"+data[name].patent_name+" "+data[name].appli_num+"</a></li>";
                                    //let more="<li id=\"excel_more\"><span class=\"excel-left\"><a href=\"javascript:void(0);\" onclick=\"excelExport()\">导出</a></span> <span class=\"more-right\"><a href=\"/collection\">查看全部</a></span> </li>";
                                    //console.log(data);
                                    $("#starList").append(starList);
                                }
                                let more="<li id=\"excel_more\"><span class=\"excel-left\"><a href=\"javascript:void(0);\" onclick=\"excelExport()\">导出</a></span> <span class=\"more-right\"><a href=\"/collection\">查看全部</a></span> </li>";
                                $("#starList").append(more);
                            }
                            else{
                                let notList="<li><h3 style=\"padding:16px;\">暂无专利</h3></li>";
                                $("#starList").append(notList);
                            }
                            
                            
                        },
                        error:function(request, errorType, errorMessage) {
                            console.log(request);
                            console.log(errorType);
                            console.log(errorMessage);
                        }
                    })
                    }
            </script>
{% endblock %}
</body>
</html>

law_regulate/templates/law_regulate/laws_search.html
{% extends 'law_regulate\base.html' %}
{% load filtrate %}
{% load staticfiles %}
{% block laws %}
<div class="col-md-2"></div>
<div class="col-md-8 height-100p">
  <div class="col-md-12 page-header pg-header">
    <div class="col-md-3"></div>
    <div class="col-md-6 height-100p">
        <form class="col-md-12" role="search" method="GET" action="{% url 'law_regulate:law_search' %}" id="indexSearch">
            <div class="col-md-2"><i class="lawlogo fa fa-university fa-3x fa-fw"  aria-hidden="true"></i></div>
            <div class="form-group col-md-10  mt7">
                <input  type="text" class="higher col-md-12 col-sm-9 col-xs-9" name="law_title" placeholder="搜索专利" id="searchDate"  autocomplete="off">
                <a href="javascript:" name="submit" onclick="$('#indexSearch').submit();return false;" class="index-s"><i class="fa fa-search fa-2x"></i></a>        
            </div>
        </form>
    </div>
      
      <div class="col-md-3"></div>
  </div>
  <div class="col-md-12 no-pd height-100p">
        <div>
                <div class="tab-content">
                  <div role="tabpanel" class="tab-pane active" id="antitrust-law">
                        <div class="list-group local-laws">
                                <div class="col-md-12 no-pd">
                                        <div class="list-group national-laws">
                                                <a href="#" class="list-group-item active">
                                                  {{law_title}}
                                                </a>
                                                {% for lawSearch in law_information %}
                                                <a href="law_detail?laws_id={{lawSearch.fields.law_id}}&json_title={{lawSearch.fields.json_tile}}" class="list-group-item law-flag">{{lawSearch.fields.law_title}}<span class="f-right">{{lawSearch.fields.effect_time}}</span></a>
                                                {% endfor %}
                                                <!-- <a href="#" ><span class="f-right" style="color: #c8201a; margin: 1em 1em;">更多...</span></a> -->
                                        </div>
                                  </div>
                        </div>
                  </div>
                </div>
        </div>
      
  </div>
  <script>
          var lawSearch={{law_information|safe}};
          console.log(lawSearch);
  </script>
</div>
<div class="col-md-2"></div>
{% endblock%}